// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// BookController is an autogenerated mock type for the BookController type
type BookController struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *BookController) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// Fetch provides a mock function with given fields: ctx
func (_m *BookController) Fetch(ctx *gin.Context) {
	_m.Called(ctx)
}

// FetchByID provides a mock function with given fields: ctx
func (_m *BookController) FetchByID(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewBookController creates a new instance of BookController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookController(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookController {
	mock := &BookController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
